//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eclipse
    {
        public int IDEclipse { get; set; }
        public System.DateTime DataOfEclipse { get; set; }
        public System.TimeSpan StartEclipse { get; set; }
        public System.TimeSpan MaxPhase { get; set; }
        public System.TimeSpan EndEclipse { get; set; }
        public string Discription { get; set; }
    }
}
