//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planet
    {
        public int IDPlanet { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public double Mass { get; set; }
        public double Radius { get; set; }
        public int Life { get; set; }
        public int PlanetarySystem { get; set; }
        public byte[] Image { get; set; }
    
        public virtual IsThereLife IsThereLife { get; set; }
        public virtual TypeOfPlanet TypeOfPlanet { get; set; }
        public virtual PlanetarySystem PlanetarySystem1 { get; set; }
    }
}
