//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planets
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlanetsDbEntities : DbContext
    {
        public PlanetsDbEntities()
            : base("name=PlanetsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Eclipse> Eclipse { get; set; }
        public virtual DbSet<IsThereLife> IsThereLife { get; set; }
        public virtual DbSet<MessageFromUser> MessageFromUser { get; set; }
        public virtual DbSet<Planet> Planet { get; set; }
        public virtual DbSet<PlanetarySystem> PlanetarySystem { get; set; }
        public virtual DbSet<Star> Star { get; set; }
        public virtual DbSet<TypeOfPlanet> TypeOfPlanet { get; set; }
    }
}
